import React, { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import api, { session } from '../../services/api';

const formatDate=(value:string)=>new Intl.DateTimeFormat('hr-HR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(value));
export default function HistoryScreen(){
 const router=useRouter(),[items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useFocusEffect(useCallback(()=>{let alive=true; setLoading(true); session.user().then(async user=>{if(!user)return router.replace('/');try{const {data}=await api.get('/api/activities/user/'+user.id);if(alive)setItems(data.sort((a:any,b:any)=>new Date(b.timestamp).getTime()-new Date(a.timestamp).getTime()));}finally{if(alive)setLoading(false)}});return()=>{alive=false}},[router]));
 return <SafeAreaView style={styles.container} edges={['top']}><Text style={styles.title}>Moje aktivnosti</Text><Text style={styles.subtitle}>Svaki korak je dio tvoje priče.</Text>{loading?<ActivityIndicator style={{marginTop:45}} color="#1E7A5A"/>:<FlatList data={items} keyExtractor={item=>String(item.id)} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><Ionicons name="footsteps-outline" size={36} color="#1E7A5A"/><Text style={styles.emptyTitle}>Tvoja priča kreće sada.</Text><Text style={styles.emptyCopy}>Započni prvu rutu i ovdje ćeš vidjeti svoj napredak.</Text></View>} renderItem={({item})=><View style={styles.card}><View style={styles.icon}><Ionicons name="walk" size={23} color="#1E7A5A"/></View><View style={{flex:1}}><Text style={styles.type}>{item.activityType}</Text><Text style={styles.date}>{formatDate(item.timestamp)} · {item.duration} min</Text></View><View style={{alignItems:'flex-end'}}><Text style={styles.distance}>{Number(item.distance).toFixed(2)} km</Text><Text style={styles.points}>+{item.points} bodova</Text></View></View>}/>}</SafeAreaView>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F1F7F4',paddingTop:10},title:{fontSize:27,fontWeight:'900',color:'#12372A',paddingHorizontal:22},subtitle:{color:'#698278',paddingHorizontal:22,marginTop:4},list:{padding:22,paddingTop:23},card:{backgroundColor:'#FFF',borderRadius:17,padding:15,flexDirection:'row',alignItems:'center',gap:12,marginBottom:11},icon:{height:46,width:46,borderRadius:14,backgroundColor:'#EAF7F0',justifyContent:'center',alignItems:'center'},type:{fontSize:16,fontWeight:'800',color:'#12372A'},date:{fontSize:12,color:'#698278',marginTop:3},distance:{fontWeight:'900',color:'#12372A'},points:{fontSize:12,color:'#1E7A5A',fontWeight:'700',marginTop:3},empty:{alignItems:'center',backgroundColor:'#FFF',borderRadius:22,padding:30,marginTop:16},emptyTitle:{fontSize:17,fontWeight:'800',color:'#12372A',marginTop:14},emptyCopy:{textAlign:'center',lineHeight:20,color:'#698278',marginTop:6}});
